version: "3.8"

volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.104.1
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgresql-ckocnu
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=123456
    volumes:
      - n8n_storage:/home/node/.n8n
