[variables]
main_domain = "${domain}"

[config]
mounts = []

[[config.domains]]
serviceName = "n8n"
port = 5678
host = "${main_domain}"

[config.env]
N8N_HOST = "${main_domain}"
N8N_PORT = "5678"
GENERIC_TIMEZONE = "America/Santo_Domingo"
POSTGRES_DB = "n8n_db"
POSTGRES_USER = "n8n"
POSTGRES_PASSWORD = "654Qp0xLjQ9t"
